<?php
require_once Constant::DEFAULT_MODULE_DIRECTORY.'biens/model/mandate.php';
class myMandate extends Mandate
{
	//SELECT * FROM Mandate m, City c WHERE (m.city_idCity = c.idCity) AND m.mandateType_idMandateType = 1 ORDER BY c.zipCode, c.name, m.priceFai

	public static function loadAll(PDO $pdo){
		$pdoStatement =  $pdo->prepare('SELECT m.idMandate, m.numberMandate, m.initDate, m.deadDate, m.address, m.priceFai, m.priceSeller, m.commission, m.estimationFai, m.margeNegociation, m.referenceCadastreParcelle1, m.referenceCadastreParcelle2, m.referenceCadastreParcelle3, m.autreReferenceParcelle, m.superficieParcelle1, m.superficieParcelle2, m.superficieParcelle3, m.superficieAutreParcelle, m.superficieConstructible, m.superficieNonConstructible, m.superficieTotale, m.numberLot, m.sHONAccordee, m.reglementDeLotissement, m.eRNT, m.passageEau, m.passageElectricite, m.passageGaz, m.voirie, m.tailleFacade, m.profondeurTerrain, m.commentaire, m.geolocalisation, m.proximiteEcole, m.proximiteCommerce, m.proximiteTransport, m.commentaireApparent, m.nbPiece, m.surfaceHabitable, m.nbChambre, m.surfacePieceVie, m.niveau, m.anneeConstruction, m.chargesMensuelle, m.taxesFonciere, m.taxeHabitation, m.user_idUser, m.sector_idSector, m.city_idCity, m.notary_idNotary, m.mandateType_idMandateType, m.transactionType_idTransactionType, m.etap_idMandateEtap, m.freeDate, m.zoneBDF, m.ligneDeCrete, m.zoneInondable, m.dPValide, m.dateDeclarationPrealable, m.prorogationDPJusquau, m.cuValide, m.dateCU, m.prorogationCUJusquau, m.cuOPSValide, m.dateCuOPS, m.prorogationCuOPSJusquau, m.permisDamenagerValide, m.datePermisDamenager, m.terrainVenduViabilise, m.terrainVenduSemiViabilise, m.terrainVenduNonViabilise, m.toutALegout, m.assainissementParFosseSceptique, m.coupCoeur, m.nouveaute, m.cheminee, m.cuisineEquipee, m.cuisineAmenagee, m.piscine, m.poolHouse, m.terrasse, m.mezzanine, m.dependance, m.gaz, m.cave, m.sousSol, m.garage, m.parking, m.rezDeJardin, m.plainPied, m.carriere, m.pointEau, m.slope_idMandateSlope, m.orientation_idMandateOrientation, m.insulation_idMandateInsulation, m.news_idMandateNews, m.heating_idMandateHeating, m.commonOwnership_idMandateCommonOwnership, m.roof_idMandateRoof, m.condition_idMandateCondition, m.style_idMandateStyle, m.construction_idMandateConstructionType, m.sanitationCorresponding_idMandateSanitationCorresponding, m.electricCorresponding_idMandateElectricCorresponding, m.gazCorresponding_idMandateGazCorresponding, m.waterCorresponding_idMandateWaterCorresponding, m.cos_idMandateCOS, m.zonagePLU_idMandateZonagePLU, m.zonageRNU_idMandateZonageRNU, m.bornageTerrain_idMandateBornageTerrain, m.geometer_idMandateGeometer, m.nature_idMandateNature,m.estimationMaxi,m.pubInternet FROM Mandate m, '.
		'City c WHERE (m.city_idCity = c.idCity) AND m.mandateType_idMandateType = '.Constant::ID_PLOT_OF_LAND.' AND m.transactionType_idTransactionType = 2 AND m.etap_idMandateEtap = '.Constant::ID_ETAP_TO_SELL.' ORDER BY c.zipCode, c.name, m.priceFai');                    
			
		//		echo 'SELECT m.idMandate, m.numberMandate, m.initDate, m.deadDate, m.address, m.priceFai, m.priceSeller, m.commission, m.estimationFai, m.margeNegociation, m.referenceCadastreParcelle1, m.referenceCadastreParcelle2, m.referenceCadastreParcelle3, m.autreReferenceParcelle, m.superficieParcelle1, m.superficieParcelle2, m.superficieParcelle3, m.superficieAutreParcelle, m.superficieConstructible, m.superficieNonConstructible, m.superficieTotale, m.numberLot, m.sHONAccordee, m.reglementDeLotissement, m.eRNT, m.passageEau, m.passageElectricite, m.passageGaz, m.voirie, m.tailleFacade, m.profondeurTerrain, m.commentaire, m.geolocalisation, m.proximiteEcole, m.proximiteCommerce, m.proximiteTransport, m.commentaireApparent, m.nbPiece, m.surfaceHabitable, m.nbChambre, m.surfacePieceVie, m.niveau, m.anneeConstruction, m.chargesMensuelle, m.taxesFonciere, m.taxeHabitation, m.user_idUser, m.sector_idSector, m.city_idCity, m.notary_idNotary, m.mandateType_idMandateType, m.transactionType_idTransactionType, m.etap_idMandateEtap, m.freeDate, m.zoneBDF, m.ligneDeCrete, m.zoneInondable, m.dPValide, m.dateDeclarationPrealable, m.prorogationDPJusquau, m.cuValide, m.dateCU, m.prorogationCUJusquau, m.cuOPSValide, m.dateCuOPS, m.prorogationCuOPSJusquau, m.permisDamenagerValide, m.datePermisDamenager, m.terrainVenduViabilise, m.terrainVenduSemiViabilise, m.terrainVenduNonViabilise, m.toutALegout, m.assainissementParFosseSceptique, m.coupCoeur, m.nouveaute, m.cheminee, m.cuisineEquipee, m.cuisineAmenagee, m.piscine, m.poolHouse, m.terrasse, m.mezzanine, m.dependance, m.gaz, m.cave, m.sousSol, m.garage, m.parking, m.rezDeJardin, m.plainPied, m.carriere, m.pointEau, m.slope_idMandateSlope, m.orientation_idMandateOrientation, m.insulation_idMandateInsulation, m.news_idMandateNews, m.heating_idMandateHeating, m.commonOwnership_idMandateCommonOwnership, m.roof_idMandateRoof, m.condition_idMandateCondition, m.style_idMandateStyle, m.construction_idMandateConstructionType, m.sanitationCorresponding_idMandateSanitationCorresponding, m.electricCorresponding_idMandateElectricCorresponding, m.gazCorresponding_idMandateGazCorresponding, m.waterCorresponding_idMandateWaterCorresponding, m.cos_idMandateCOS, m.zonagePLU_idMandateZonagePLU, m.zonageRNU_idMandateZonageRNU, m.bornageTerrain_idMandateBornageTerrain, m.geometer_idMandateGeometer, m.nature_idMandateNature,m.estimationMaxi,m.pubInternet FROM Mandate m, '.
		//		'City c WHERE (m.city_idCity = c.idCity) AND m.mandateType_idMandateType = '.Constant::ID_PLOT_OF_LAND.' AND m.transactionType_idTransactionType = '.CONSTANT::ID_ETAP_TO_SELL.' ORDER BY c.zipCode, c.name, m.priceFai';
		if (!$pdoStatement->execute()) {
			throw new Exception('Erreur lors du chargement de tous/toutes les mandates depuis la base de donn�es');
		}

		$mandates = array();
		while ($mandate = Mandate::fetch($pdo,$pdoStatement,$easyload)) {
			$mandates[] = $mandate;
		}

		// Retourner le tableau
		return $mandates;
	}
}